#!/bin/bash

case "$1" in
  build)
    ./bin/build_all
    ;;
  test)
    ./bin/test_all
    ;;
  scripts)
    ./bin/clean_all
    ./bin/script_all "$2"
    ;;
  *)
    echo "Usage: $0 {build|test} | scripts [script name]"
esac